### ISSUE TITLE
Setup project structure and initial configs

### ISSUE THREAD

**Issue by Andr3wKaranja** [hakken-org/ceres#1]
The goal of this **task** is to provide a foundation for further development by creating a starting point for the project - This will enable us to begin building the platform and working on more specific features and functionality.

**Comment by Andr3wKaranja** [comment]
In that regard, Here's what I propose 

- Essential files & directories, initial config settings, and any necessary deps. 
- Configure a basic authentication and authorization system
- 

-

**Comment by wxmbugu** [comment]
I'm closing this issue because we are going to start by implementing & designing the peer to peer network

**Comment by Andr3wKaranja** [comment]
Ume reopen issue?

**Comment by wxmbugu** [comment]
if you have any input you can add it if not we close the issue
